//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace RandomLevel
{
	/// <summary>
	/// A coordinate class, to specify a coordinate in the map
	/// </summary>
	public class Coordinate {
		public int row { get; set;}
		public int col { get; set;}
		/// <summary>
		/// Initializes a new instance of the <see cref="RandomLevel.Coordinate"/> class.
		/// </summary>
		/// <param name="_row"> The row coordinate.</param>
		/// <param name="_col"> The column coordinate.</param>
		public Coordinate(int _row, int _col){
			row = _row;
			col = _col;
		}
	}
}

