//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;
namespace RandomLevel
{
	public class RandomLevelRenderer : MonoBehaviour
	{
		private SquareGraph sg;
		private Vector3 targetVec;
		public GameObject emitterPrefab, wallPrefab, targetPrefab;
		public int rows, cols;
		private Quadrant quad;
		public const float ScaleFact = 15f;
		private void Render() 
		{
			for (int i = 0; i < sg.maxrow; i++) 
			{
				for (int j = 0; j < sg.maxcol; j++) 
				{
					Coordinate c = new Coordinate(i,j);
					Vertex v = sg.GetVertexAtCoords(c);
					Vector3 spawnVec = CoordToVector(c) - targetVec;
					InstantiateObject(v,spawnVec);
				}
			}
		}
		static Vector3 CoordToVector(Coordinate c) 
		{
			return new Vector3 (c.col*ScaleFact, 0f, c.row*-ScaleFact);
		}
		void InstantiateObject(Vertex v, Vector3 spawnVec)
		{

			if (v.prop == Property.LASER) 
			{
				int i = DetermineQuadRotation (quad);
				Quaternion q = Quaternion.Euler(0, i*90, 0);
				Instantiate (emitterPrefab, spawnVec, q);
			} 
			else if (v.prop == Property.WALL) 
			{
				Quaternion q = Quaternion.Euler(0, UnityEngine.Random.Range(0,4)*90, 0);
				Instantiate (wallPrefab, spawnVec, q);
			} 
			else if (v.prop == Property.TARGET) 
			{
				Instantiate (targetPrefab, spawnVec, Quaternion.identity);
			}
		}
		public void Start() 
		{
			RandomLevelGenerator rlg = new RandomLevelGenerator (rows, cols);
			quad = rlg.q;
			sg = rlg.ReturnRandomMap ();
			targetVec = CoordToVector (rlg.targetCoord);
			Render ();
		}
		static int DetermineQuadRotation(Quadrant q) 
		{
			switch (q) 
			{
			case Quadrant.NORTHWEST: return 3;
			case Quadrant.SOUTHWEST: return 0;
			case Quadrant.SOUTHEAST: return 1;
			case Quadrant.NORTHEAST: return 2;
			default: throw new ArgumentException("The parameter should be a valid quadrant value.");
			}
		}
	}
}

