//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace NetworkPhoton
{
	public class NetworkManager : MonoBehaviour
	{
		public NetworkManager ()
		{
		}
		void Start()
		{
			PhotonNetwork.ConnectUsingSettings("0.1");
		}
	}
}

