//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AssemblyCSharpEditor.Tests.RandomLevels
{
	using System;
	using RandomLevel;
	using NUnit.Framework;
	[TestFixture]
	public class PathBuildTesting
	{
		[Test]
		[ExpectedException(typeof(System.ArgumentNullException))]
		public void PathBuilderConstructionNullSGTest() {
			PathBuilder pb = new PathBuilder (null, new Coordinate (0, 0));
		}
		[Test]
		[ExpectedException(typeof(System.ArgumentNullException))]
		public void PathBuilderConstructionNullCoordTest() {
			PathBuilder pb = new PathBuilder (new SquareGraph(1,1), null);
		}
	}
}

