//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AssemblyCSharpEditor.Tests.RandomLevels
{
	using System;
	using RandomLevel;
	using NUnit.Framework;
	[TestFixture]
	public class SquareGraphTesting
	{
		[Test]
		[ExpectedException(typeof(ArgumentException))]
		public void SqGraphTestRowsIsZero() {
			SquareGraph sg = new SquareGraph (0, 20);
		}
	}
}

